### ISSUE TITLE
Kytos shouldn't send packet_out for Noviflow's BFD logical ports

### ISSUE THREAD

**Issue by gleybersonandrade** [kytos/of_core#79]
In Noviflow switches, the logicalports type BFD does not accept OUTPUT action nor MATCH (but a group can be set up to watch a BFD logicalport).

How to detect this type of port? (needs info)

**Comment by italovalcy** [comment]
Hi guys, in my opinion, one way to do this is by looking at the supported, current and max speed, which may be a good indication about if the port can be used to actually forward traffic. Thus, if all the flags are empty (zero) - supported=0 && cur_speed=0 && max_speed=0 - then it might be the case the port does not support packet_out. So for those ports, Kytos could change the default configuration for a new port to "not send packet_out". Then, it will be up to the network operator to reenable it (this is important because current LAG ports are coming also with speed zero - but we have an open issue to address this).
